Add Blog to Nav
arconnectio/landing pull request #14
Opened 2024-05-20 14:03 UTC by MattClabs

Add blog to ArConnect.io Nav

2024-05-20 14:06 UTC, 7i7o requested changes
Left a comment in the file 😊

2024-05-20 14:06 UTC, 7i7o commented on src/components/Nav.tsx
> +                <NavLink
Before this line you forgot to close the previous `<NavLink>` tag with a `</NavLink>`

2024-05-20 15:11 UTC, 7i7o requested changes
Last detail

2024-05-20 15:11 UTC, 7i7o commented on src/components/Nav.tsx
Great! Now we should change Line 31 for responsiveness to accommodate a new link.
I think maybe changing from 720px to 800px would do. 

<img width="744" alt="Screenshot 2024-05-20 at 5 08 19 PM" src="https://github.com/arconnectio/landing/assets/84824996/e04db023-68d5-4e61-824f-b54612f54e1f">

<img width="811" alt="Screenshot 2024-05-20 at 5 08 07 PM" src="https://github.com/arconnectio/landing/assets/84824996/7407f7c7-f6c5-4999-936e-2fdb5f172236">

2024-05-20 15:17 UTC, nicholaswma commented on src/components/Nav.tsx
> +                  target="_blank"
do we want this link to open a new tab or just redirect them to '/blog'?

2024-05-20 15:18 UTC, MattClabs commented on src/components/Nav.tsx
> +                  target="_blank"
@nicholaswma I don't have a preference either way

2024-05-20 15:18 UTC, MattClabs commented on src/components/Nav.tsx
I think I fixed this @7i7o

2024-05-20 15:34 UTC, 7i7o commented on src/components/Nav.tsx
> +                  target="_blank"
For a little more consistency while navigating these links, it would be nice if we remove the 
```
target="_blank"
```
and also add the Blog <NavLink> to the Blog's NavBar

That way we would navigate back and forth from Home to Blog, keeping a familiar NavBar without opening a new tab each time we open the Blog. Wdyt?
@MattClabs

2024-05-20 19:14 UTC, 7i7o requested changes

2024-05-20 19:14 UTC, 7i7o commented on src/components/Nav.tsx
> +                  target="_blank"
@MattClabs Additional to this, I missed that you should be using the relative path instead of the absolute one.
In this case:

```
                  href="/blog"
```

would be the correct one, since that route is part of this repo.

The docs link is missleading if you were copying the code.
That one makes sense to be an absolute path that pops up a tab because it's an external link (by external I mean it's not part of this repo and hosted in gitbook instead).

2024-05-21 13:52 UTC, MattClabs commented on src/components/Nav.tsx
> +                  target="_blank"
@7i7o changed the href and removed the target blank.  

And checking out the latest vercel deployment, I think the UX for the nav is matching what you described above

2024-05-21 17:08 UTC, 7i7o commented on src/components/Nav.tsx
> +                  target="_blank"
@MattClabs FYI I just set back the media-query to 720px because the whole app (several components) relies on that value.
It was easier to make the NavLinks fit in 720px than it was to change the whole landing to 800px.
lmk if the spacing between NavLinks is ok.

You can see the specific changes in the [last commit](https://github.com/arconnectio/landing/pull/14/commits/47e5bc4f7ab8d71096de87e1c698c6ac63296bf9) if you want to learn where the spacing was set in the styles

2024-05-21 17:08 UTC, 7i7o approved these changes
Great work @MattClabs ! LGTM 🚀

2024-05-21 17:11 UTC, merged